version: '3.8'

services:
  api:
    container_name: todolist_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python api/manage.py runserver 0.0.0.0:${API_PORT:-8000}
    volumes:
      - .:/app/
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - ./.env.dev
    networks:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: todolist_postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /data/postgres
    volumes:
       - .docker/postgres:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  postgres:
    driver: bridge

